name: HACS Validation

on:
  pull_request:
  push:

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "integration"
